/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'dateKey' : IDL.Text,
  'username' : IDL.Text,
  'note' : IDL.Text,
  'durationHours' : IDL.Nat,
  'emoji' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });

export const idlService = IDL.Service({
  'addActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteActivity' : IDL.Func([IDL.Nat], [], []),
  'getActivitiesForDateRange' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Nat), IDL.Text))],
      ['query'],
    ),
  'getActivitiesForDay' : IDL.Func([IDL.Text], [IDL.Vec(Activity)], ['query']),
  'getUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'joinActivity' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'login' : IDL.Func([IDL.Text], [IDL.Text, Role], []),
  'purgeOldActivities' : IDL.Func([IDL.Text], [], []),
  'removeUser' : IDL.Func([IDL.Text], [], []),
  'updateActivityTime' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'dateKey' : IDL.Text,
    'username' : IDL.Text,
    'note' : IDL.Text,
    'durationHours' : IDL.Nat,
    'emoji' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  
  return IDL.Service({
    'addActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteActivity' : IDL.Func([IDL.Nat], [], []),
    'getActivitiesForDateRange' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Nat), IDL.Text))],
        ['query'],
      ),
    'getActivitiesForDay' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'joinActivity' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'login' : IDL.Func([IDL.Text], [IDL.Text, Role], []),
    'purgeOldActivities' : IDL.Func([IDL.Text], [], []),
    'removeUser' : IDL.Func([IDL.Text], [], []),
    'updateActivityTime' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };