/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'startTime' : string,
  'dateKey' : string,
  'username' : string,
  'durationHours' : bigint,
  'emoji' : string,
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'author' : string,
  'timestamp' : bigint,
  'threadId' : string,
}
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface _SERVICE {
  'addActivity' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'addGpxFile' : ActorMethod<[string, string, string], bigint>,
  'addMessage' : ActorMethod<[string, string, string], bigint>,
  'addUser' : ActorMethod<[string, string, string], undefined>,
  'deleteActivity' : ActorMethod<[bigint], boolean>,
  'deleteGpxFile' : ActorMethod<[bigint], boolean>,
  'getActivitiesFiltered' : ActorMethod<[string, string], Array<Activity>>,
  'getActivitiesForDay' : ActorMethod<[string], Array<Activity>>,
  'getGpxContent' : ActorMethod<[bigint], string>,
  'getGpxFiles' : ActorMethod<[], Array<[bigint, string, string, bigint]>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getUsers' : ActorMethod<[], Array<[string, string, string]>>,
  'joinActivity' : ActorMethod<[bigint, string], bigint>,
  'login' : ActorMethod<[string], [string, Role]>,
  'purgeOldActivities' : ActorMethod<[string], boolean>,
  'removeUser' : ActorMethod<[string], undefined>,
  'setVisibility' : ActorMethod<[bigint, string], undefined>,
  'updateActivityTime' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];