/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Activity {
    id: bigint;
    startTime: string;
    dateKey: string;
    username: string;
    durationHours: bigint;
    emoji: string;
}
export interface Message {
    id: bigint;
    threadId: string;
    author: string;
    text: string;
    timestamp: bigint;
}
export enum Role {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    addActivity(dateKey: string, username: string, startTime: string, emoji: string, durationHours: bigint): Promise<bigint>;
    addMessage(threadId: string, author: string, text: string): Promise<bigint>;
    getMessages(threadId: string): Promise<Array<Message>>;
    addUser(name: string, pin: string, color: string): Promise<void>;
    deleteActivity(activityId: bigint): Promise<boolean>;
    getActivitiesForDay(dateKey: string): Promise<Array<Activity>>;
    getActivitiesFiltered(dateKey: string, callerUsername: string): Promise<Array<Activity>>;
    setVisibility(activityId: bigint, vis: string): Promise<void>;
    getUsers(): Promise<Array<[string, string, string]>>;
    joinActivity(existingActivityId: bigint, username: string): Promise<bigint>;
    login(pin: string): Promise<[string, Role]>;
    purgeOldActivities(todayKey: string): Promise<boolean>;
    removeUser(name: string): Promise<void>;
    updateActivityTime(activityId: bigint, newStartTime: string): Promise<boolean>;
    addGpxFile(username: string, filename: string, content: string): Promise<bigint>;
    getGpxFiles(): Promise<Array<[bigint, string, string, bigint]>>;
    getGpxContent(fileId: bigint): Promise<string>;
    deleteGpxFile(fileId: bigint): Promise<boolean>;
}
import type { Role as _Role } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMessage(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async addUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteActivity(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async getActivitiesForDay(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesForDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesForDay(arg0);
            return result;
        }
    }
    async getActivitiesFiltered(arg0: string, arg1: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesFiltered(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesFiltered(arg0, arg1);
            return result;
        }
    }
    async setVisibility(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.setVisibility(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.setVisibility(arg0, arg1);
        }
    }
    async getUsers(): Promise<Array<[string, string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return result;
        }
    }
    async joinActivity(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.joinActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinActivity(arg0, arg1);
            return result;
        }
    }
    async login(arg0: string): Promise<[string, Role]> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return [
                    result[0],
                    from_candid_Role_n1(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return [
                result[0],
                from_candid_Role_n1(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async purgeOldActivities(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.purgeOldActivities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purgeOldActivities(arg0);
            return result;
        }
    }
    async removeUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async updateActivityTime(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivityTime(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivityTime(arg0, arg1);
            return result;
        }
    }
    async addGpxFile(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).addGpxFile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).addGpxFile(arg0, arg1, arg2);
            return result;
        }
    }
    async getGpxFiles(): Promise<Array<[bigint, string, string, bigint]>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getGpxFiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getGpxFiles();
            return result;
        }
    }
    async getGpxContent(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getGpxContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getGpxContent(arg0);
            return result;
        }
    }
    async deleteGpxFile(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).deleteGpxFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).deleteGpxFile(arg0);
            return result;
        }
    }
}
function from_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
